// Chatlog Engine v3 — parses Claude Code session JSONL into one document:
//   chatlog.md — all sessions with main index + activity sections (gap-based)
//
// Output location: repo root (state file alongside CONTEXT.md)
//
// Usage:
//   node projects/auto-chatlog/chatlog-engine.js           # with abstracts from abstracts.json
//   node projects/auto-chatlog/chatlog-engine.js --digest   # only generate digest (for subagent)
//   node projects/auto-chatlog/chatlog-engine.js --input-dir /path/to/sessions --output /path/to/chatlog.md
//   node projects/auto-chatlog/chatlog-engine.js --input-dir /path --output /path --digest
//
// Timestamps: Danish time (Europe/Copenhagen)
// Section breaks: 90+ minute gap between messages (across sessions)
// Abstracts: generated by subagent, stored in abstracts.json

const fs = require("fs");
const path = require("path");

const DEFAULT_PROJECT_DIR =
  "c:/Users/Krist/.claude/projects/c--Users-Krist-dev-projects-Yggdra";
const DEFAULT_OUTPUT_FILE = path.resolve(__dirname, "../../chatlog.md");
const ABSTRACTS_FILE = path.resolve(__dirname, "abstracts.json");
const DIGEST_FILE = path.resolve(__dirname, "sections-digest.json");
const PATTERNS_FILE = path.resolve(__dirname, "redact-patterns.json");
const TIMEZONE = "Europe/Copenhagen";
const GAP_THRESHOLD_MS = 90 * 60 * 1000; // 90 minutes

const DANISH_DAYS = [
  "søndag", "mandag", "tirsdag", "onsdag", "torsdag", "fredag", "lørdag",
];

// --- Secret redaction ---

const BUILTIN_PATTERNS = [
  { regex: /ntn_[A-Za-z0-9_-]{20,}/g, label: "NOTION_TOKEN" },
  { regex: /sk-[A-Za-z0-9_-]{20,}/g, label: "API_KEY" },
  { regex: /ghp_[A-Za-z0-9]{36,}/g, label: "GITHUB_TOKEN" },
  { regex: /xoxb-[A-Za-z0-9-]{20,}/g, label: "SLACK_TOKEN" },
  { regex: /gho_[A-Za-z0-9]{36,}/g, label: "GITHUB_OAUTH" },
  { regex: /xoxp-[A-Za-z0-9-]{20,}/g, label: "SLACK_USER_TOKEN" },
  { regex: /AKIA[A-Z0-9]{16}/g, label: "AWS_KEY" },
];

function loadDynamicPatterns() {
  try {
    const data = JSON.parse(fs.readFileSync(PATTERNS_FILE, "utf8"));
    return data.map((p) => ({
      regex: new RegExp(p.regex, p.flags || "g"),
      label: p.label,
    }));
  } catch (e) {
    return [];
  }
}

const dynamicPatterns = loadDynamicPatterns();
const ALL_PATTERNS = [...BUILTIN_PATTERNS, ...dynamicPatterns];

function redactSecrets(text) {
  for (const { regex, label } of ALL_PATTERNS) {
    regex.lastIndex = 0;
    text = text.replace(regex, `[${label}]`);
  }
  return text;
}

// Heuristic: find strings that look like API tokens but aren't covered by known patterns
function scanSuspiciousTokens(text) {
  const found = [];
  // Pattern: short_prefix + underscore + long alphanum (e.g. fc_abc123def456...)
  // Must use underscore (not hyphen — hyphens catch URLs and slugs)
  const prefixPattern = /\b([a-z]{2,6}_)[A-Za-z0-9]{20,}\b/g;
  let match;
  while ((match = prefixPattern.exec(text)) !== null) {
    const token = match[0];
    const prefix = match[1];
    // Skip tool call IDs and known non-secrets
    if (prefix === "toolu_") continue;
    if (prefix === "msg_") continue;
    if (prefix === "chatcmpl_") continue;
    // Skip if already covered by known patterns
    const covered = ALL_PATTERNS.some((p) => {
      p.regex.lastIndex = 0;
      return p.regex.test(token);
    });
    if (!covered) found.push(token);
  }
  return [...new Set(found)];
}

// --- Time helpers ---

function toDanish(utcTimestamp) {
  const d = new Date(utcTimestamp);
  const parts = new Intl.DateTimeFormat("sv-SE", {
    timeZone: TIMEZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  }).formatToParts(d);

  const get = (type) => parts.find((p) => p.type === type)?.value || "??";
  return {
    date: `${get("year")}-${get("month")}-${get("day")}`,
    time: `${get("hour")}:${get("minute")}`,
    hour: parseInt(get("hour"), 10),
    fullISO: d.toISOString(),
  };
}

function danishNow() {
  return toDanish(new Date().toISOString());
}

function danishDayName(dateStr) {
  // dateStr = "2026-03-13"
  const d = new Date(dateStr + "T12:00:00");
  return DANISH_DAYS[d.getDay()];
}

function formatDanishDate(dateStr) {
  // "2026-03-13" → "torsdag d. 13/3-2026"
  const [year, month, day] = dateStr.split("-");
  const dayName = danishDayName(dateStr);
  return `${dayName} d. ${parseInt(day)}/${parseInt(month)}-${year}`;
}

// --- Parse all sessions ---

function parseSessionFiles(inputDir) {
  const files = fs
    .readdirSync(inputDir)
    .filter((f) => f.endsWith(".jsonl"))
    .map((f) => path.join(inputDir, f));

  if (files.length === 0) {
    console.error("No session files found.");
    process.exit(1);
  }

  console.log(`Reading ${files.length} session file(s)...`);
  const messages = [];

  for (const file of files) {
    const sessionId = path.basename(file, ".jsonl").substring(0, 8);
    const lines = fs
      .readFileSync(file, "utf8")
      .split("\n")
      .filter((l) => l.trim());

    for (const line of lines) {
      try {
        const entry = JSON.parse(line);
        const msg = entry.message || {};
        const role = msg.role;
        if (role !== "user" && role !== "assistant") continue;

        let content = msg.content || "";
        if (Array.isArray(content)) {
          content = content
            .filter((b) => b.type === "text")
            .map((b) => b.text)
            .join("\n");
        }
        content = content.trim();
        if (!content) continue;

        // Skip system noise
        if (content.startsWith("<system-reminder>")) continue;
        if (content.startsWith("<ide_")) continue;
        if (content.startsWith("<local-command")) continue;
        if (content.startsWith("<command-name>")) continue;

        // Redact secrets (built-in + dynamic patterns)
        content = redactSecrets(content);

        const danish = toDanish(
          entry.timestamp || "1970-01-01T00:00:00Z",
        );

        messages.push({
          timestamp: entry.timestamp || "1970-01-01T00:00:00",
          tsMs: new Date(entry.timestamp || "1970-01-01T00:00:00Z").getTime(),
          date: danish.date,
          time: danish.time,
          hour: danish.hour,
          role,
          content,
          sessionId,
        });
      } catch (e) {}
    }
  }

  messages.sort((a, b) => a.tsMs - b.tsMs);
  return messages;
}

// --- Gap-based sectioning ---

function splitIntoSections(messages) {
  if (messages.length === 0) return [];

  const sections = [];
  let current = [messages[0]];

  for (let i = 1; i < messages.length; i++) {
    const gap = messages[i].tsMs - messages[i - 1].tsMs;
    if (gap >= GAP_THRESHOLD_MS) {
      sections.push(current);
      current = [messages[i]];
    } else {
      current.push(messages[i]);
    }
  }
  sections.push(current);
  return sections;
}

// --- Load abstracts ---

function loadAbstracts() {
  try {
    return JSON.parse(fs.readFileSync(ABSTRACTS_FILE, "utf8"));
  } catch (e) {
    return {};
  }
}

// --- Generate chatlog.md ---

function generateChatlog(messages) {
  const sections = splitIntoSections(messages);
  const abstracts = loadAbstracts();
  const now = danishNow();

  // Group sections by date
  const dateMap = {};
  sections.forEach((section, idx) => {
    const firstMsg = section[0];
    const lastMsg = section[section.length - 1];
    const date = firstMsg.date;
    if (!dateMap[date]) dateMap[date] = [];
    dateMap[date].push({
      sectionIndex: idx,
      firstTime: firstMsg.time,
      lastTime: lastMsg.time,
      count: section.length,
    });
  });

  const dates = Object.keys(dateMap).sort();

  // Get date-level abstracts (key: "date:YYYY-MM-DD") and section abstracts (key: "0", "1", ...)
  function getDateAbstract(date) {
    return abstracts[`date:${date}`] || null;
  }
  function getSectionAbstract(idx) {
    return abstracts[String(idx)] || null;
  }

  // --- Main index ---
  const title = cliTitle || "Chatlog — Yggdra";
  let md = `# ${title}\n\n`;
  md += `**Sidst opdateret:** ${now.date} ${now.time}  \n`;
  md += `**Sektioner:** ${sections.length} · **Beskeder:** ${messages.length}\n\n`;
  md += `## Hovedindeks\n\n`;

  for (const date of dates) {
    const daySections = dateMap[date];
    const totalMsgs = daySections.reduce((s, d) => s + d.count, 0);
    const prettyDate = formatDanishDate(date);
    const dateAbstract = getDateAbstract(date);

    md += `### [${prettyDate}](#dato-${date}) (${totalMsgs} beskeder)\n\n`;
    if (dateAbstract) {
      md += `${dateAbstract}\n\n`;
    }

    for (const sec of daySections) {
      const anchor = `sektion-${sec.sectionIndex}`;
      const secAbstract = getSectionAbstract(sec.sectionIndex);
      const abstractText = secAbstract || "";
      md += `- [kl. ${sec.firstTime}–${sec.lastTime}](#${anchor}) (${sec.count})`;
      if (abstractText) md += ` — ${abstractText}`;
      md += `\n`;
    }
    md += `\n`;
  }

  md += `---\n\n`;

  // --- Date + section rendering ---
  let currentDate = null;

  for (let idx = 0; idx < sections.length; idx++) {
    const section = sections[idx];
    const firstMsg = section[0];
    const lastMsg = section[section.length - 1];
    const date = firstMsg.date;

    // Date header (only when date changes)
    if (date !== currentDate) {
      currentDate = date;
      const dateIdx = dates.indexOf(date);
      const prevDate = dateIdx > 0 ? dates[dateIdx - 1] : null;
      const nextDate = dateIdx < dates.length - 1 ? dates[dateIdx + 1] : null;
      const prettyDate = formatDanishDate(date);

      md += `## ${prettyDate} <a id="dato-${date}"></a>\n\n`;

      const navParts = [];
      if (prevDate) navParts.push(`[← ${formatDanishDate(prevDate)}](#dato-${prevDate})`);
      navParts.push(`[Hovedindeks](#hovedindeks)`);
      if (nextDate) navParts.push(`[${formatDanishDate(nextDate)} →](#dato-${nextDate})`);
      md += navParts.join(" | ") + "\n\n";
    }

    // Section header
    const sessions = [...new Set(section.map((m) => m.sessionId))];
    const secAbstract = getSectionAbstract(idx);
    const anchor = `sektion-${idx}`;

    md += `### kl. ${firstMsg.time}–${lastMsg.time} <a id="${anchor}"></a>\n\n`;
    md += `**${section.length} beskeder** · Sessions: ${sessions.join(", ")}\n\n`;
    if (secAbstract) {
      md += `> ${secAbstract}\n\n`;
    }

    // Messages
    for (const msg of section) {
      const prefix = msg.role === "user" ? "YTTRE" : "CLAUDE";
      let content = msg.content;
      if (content.length > 5000)
        content = content.substring(0, 5000) + "\n...[truncated]";
      md += `#### ${prefix} — ${msg.time}\n\n${content}\n\n---\n\n`;
    }
  }

  return md;
}

// --- Generate sections digest for subagent ---

function generateDigest(messages) {
  const sections = splitIntoSections(messages);

  // Group by date for date-level digests
  const dateMap = {};
  const sectionDigests = sections.map((section, idx) => {
    const firstMsg = section[0];
    const lastMsg = section[section.length - 1];
    const date = firstMsg.date;
    if (!dateMap[date]) dateMap[date] = [];

    const userMsgs = section
      .filter((m) => m.role === "user")
      .slice(0, 10)
      .map((m) => {
        const text = m.content.substring(0, 300);
        return `[${m.time}] ${text}`;
      });
    const assistantMsgs = section
      .filter((m) => m.role === "assistant")
      .slice(0, 5)
      .map((m) => {
        const text = m.content.substring(0, 200);
        return `[${m.time}] ${text}`;
      });

    const digest = {
      id: idx,
      date: firstMsg.date,
      timeRange: `${firstMsg.time}–${lastMsg.time}`,
      msgCount: section.length,
      userSamples: userMsgs,
      assistantSamples: assistantMsgs,
    };

    dateMap[date].push(digest);
    return digest;
  });

  // Scan all messages for suspicious tokens (pre-redaction content is already redacted,
  // so we scan the raw JSONL again for anything the built-in patterns missed)
  const allSuspicious = [];
  for (const section of sections) {
    for (const msg of section) {
      const found = scanSuspiciousTokens(msg.content);
      allSuspicious.push(...found);
    }
  }
  const uniqueSuspicious = [...new Set(allSuspicious)];

  return {
    sections: sectionDigests,
    dates: Object.keys(dateMap).sort().map((d) => ({
      date: d,
      prettyDate: formatDanishDate(d),
      sectionCount: dateMap[d].length,
      totalMsgs: dateMap[d].reduce((s, sec) => s + sec.msgCount, 0),
    })),
    suspiciousTokens: uniqueSuspicious.length > 0 ? uniqueSuspicious : undefined,
  };
}

// --- CLI args ---

function getArg(flag) {
  const idx = process.argv.indexOf(flag);
  return idx !== -1 && idx + 1 < process.argv.length ? process.argv[idx + 1] : null;
}

const args = process.argv.slice(2);
const digestOnly = args.includes("--digest");
const cliInputDir = getArg("--input-dir");
const cliOutput = getArg("--output");
const cliTitle = getArg("--title");

// --- Main ---

const inputDir = cliInputDir || DEFAULT_PROJECT_DIR;
const outputFile = cliOutput ? path.resolve(cliOutput) : DEFAULT_OUTPUT_FILE;

const now = danishNow();
console.log(`Today (Danish): ${now.date} ${now.time}`);
console.log(`Input: ${inputDir}`);
console.log(`Output: ${outputFile}`);

const messages = parseSessionFiles(inputDir);
console.log(`Parsed ${messages.length} messages total.`);

const digest = generateDigest(messages);
fs.writeFileSync(DIGEST_FILE, JSON.stringify(digest, null, 2));
console.log(`sections-digest.json: ${digest.sections.length} sections → ${DIGEST_FILE}`);

if (digest.suspiciousTokens && digest.suspiciousTokens.length > 0) {
  console.log(`\n⚠ ${digest.suspiciousTokens.length} suspicious token(s) found — subagent should review:`);
  for (const t of digest.suspiciousTokens.slice(0, 10)) {
    console.log(`  ${t.substring(0, 8)}...${t.substring(t.length - 4)} (${t.length} chars)`);
  }
}

if (!digestOnly) {
  const chatlog = generateChatlog(messages);
  fs.writeFileSync(outputFile, chatlog);
  console.log(`chatlog.md: ${messages.length} messages, ${digest.sections.length} sections → ${outputFile}`);
}

console.log("Done.");
